### ISSUE TITLE
Error messages on running.

### ISSUE THREAD

**Issue by BrandonBenn** [andykais/bitwarden-dmenu#1]
**Describe the bug**
After logging in to bitwarden-cli client, then running `bitwarden-dmenu` I received a few error messages after typing the master password into the dmenu dialog box.

**To Reproduce**
`→ bitwarden-dmenu --verbose
$ dmenu -p Password: -nf black -nb black 

$ /home/{myuser}/.node_modules/lib/node_modules/bitwarden-dmenu/node_modules/.bin/bw unlock '******' --raw 

$ /home/{myuser}/.node_modules/lib/node_modules/bitwarden-dmenu/node_modules/.bin/bw sync --last --session=******  

syncing vault... 

$ /home/{myuser}/.node_modules/lib/node_modules/bitwarden-dmenu/node_modules/.bin/bw sync --session=******  

sync complete, last sync was 2018-09-16T13:15:42.029Z 

$ /home/{myuser}/.node_modules/lib/node_modules/bitwarden-dmenu/node_modules/.bin/bw list items --session=******  

TypeError: Cannot read property 'username' of undefined
    at list.map.a (/home/{myuser}/.node_modules/lib/node_modules/bitwarden-dmenu/src/index.js:58:60)
    at Array.map (<anonymous>)
    at chooseAccount (/home/{myuser}/.node_modules/lib/node_modules/bitwarden-dmenu/src/index.js:58:29)
    at module.exports (/home/{myuser}/.node_modules/lib/node_modules/bitwarden-dmenu/src/index.js:100:33)
begin cleanup 

/tmp/bitwarden-session.txt already removed. 

$ /home/{myuser}/.node_modules/lib/node_modules/bitwarden-dmenu/node_modules/.bin/bw lock 

bitwarden is locked.
clipboard is cleared.
`

**Expected behavior**
I guess to list the items in the password vault for selection.

**Comment by andykais** [comment]
alright, so I discovered that this error occurred from this cli trying to treat a non login account like a login account. To keep the use case simple, for now this dmenu will only show login accounts and will filter all others out. Fixed in `bitwarden-dmenu@1.1.2`
