### ISSUE TITLE
Ignores dmenu font option

### ISSUE THREAD

**Issue by ibrokemypie** [andykais/bitwarden-dmenu#14]
**Describe the bug**

Adding a font to --dmenu-args or --dmenu-passwd-args like ``--dmenu-pswd-args="-i -fn 'Hack-10'" `` doesn't actually change the font

**To Reproduce**

```
bitwarden-dmenu --dmenu-pswd-args="-i -fn 'Hack-10'" --dmenu-args="-i -fn 'Hack-10'" --clear-clipboard 30 --session-timeout 500 --sync-vault-after 3600 --on-error 'xargs notify-send --urgency=low' --debug
bitwarden-dmenu v1.5.3

$ /usr/lib/node_modules/bitwarden-dmenu/node_modules/.bin/bw login --check

checking for session file at /tmp/bitwarden-session.txt

no session file found.

$ dmenu -p Password: -nf black -nb black -i -fn 'Hack-10'
```
The menu shown uses the same default small font as running just dmenu without -fn

**Expected behavior**

The menu uses the font Hack-10

**Comment by andykais** [comment]
hmm I tested this myself using the DejaVu font and the args seem to function fine. Maybe just make sure you are using the latest version?
```bash
bitwarden-dmenu  --dmenu-args="-i -fn DejaVu" --dmenu-pswd-args="-i"
```

Also doesnt hurt to check if the fonts show up without bitwarden-dmenu!
```bash
echo'hi\nthere' | dmenu -fn DejaVu
```

**Comment by ibrokemypie** [comment]
Hmm I think that it was fixed in a previous commit, I was running the latest version from the aur on arch, but it was updated a couple days ago and seems to work now I think?

**Comment by andykais** [comment]
👍 closing this then
