### ISSUE TITLE
Hitting escape locks bitwarden

### ISSUE THREAD

**Issue by AtomToast** [andykais/bitwarden-dmenu#15]
When hitting escape inside of the menu selection bitwarden just immediately locks. No matter for how long the grace period should have lasted.

## To reproduce:

- open bitwarden-dmenu with a session timeout
- Enter your password and unlock your vault
- in the item selection screen hit escape to exit dmenu

## Expected behaviour:

The menu just closes and the vault stays unlocked

## Actual behaviour:

The vault locks immediately so you have to reenter your password once you open bitwarden-dmenu again

**Comment by andykais** [comment]
nice catch! It turned out to be a one-liner change
