### ISSUE TITLE
Request: use git tags to mark releases

### ISSUE THREAD

**Issue by kauron** [andykais/bitwarden-dmenu#16]
Hi there! I'm a happy user of this repo, so much that I package it for the AUR (user-generated packages for Arch Linux).

My request is that each release should be tagged via git, which means that (1) I can get notified on each release via RSS and (2) I can download a snapshot of the repository directly from GitHub without cloning it. I'm aware that you're tagging the releases in npm, but I found no way to subscribe to those.

Thank you for your work!

**Comment by andykais** [comment]
I saw that yesterday when I was perusing for a bitwarden desktop app with `yay`! Sure, I can do that. I have been meaning to set up releases to trigger npm publishes for a while anyways

**Comment by andykais** [comment]
alrighty. Publishes are now tied to releases https://github.com/andykais/bitwarden-dmenu/releases! Ill keep this open for now since it would be cool to hear when you wire up rss feeds @kauron

**Comment by kauron** [comment]
Perfect, I've just packaged the 1.5.9 version (https://aur.archlinux.org/packages/bitwarden-dmenu/), and now I can properly subscribe to the releases. Thank you!
